### PR TITLE
Update Dockerfile.tmLanguage

### LINKED ISSUE #8: back slash breaks syntax highlighting
If I have something like

``````
RUN echo a=\"b+c\" >> test.txt
# everything below is messed up
``````
I can confirm that it's the backslash that is causing the issue because when I remove them the syntax highlighting goes back to normal

### PR DESCRIPTION
**Pull request by princemaple**
Accept escaped chars on top level, fixes #8 on the tmLanguage side

Maybe someone will want to refactor it...

### CODE REVIEW

**Comment by princemaple** [comment]
related to #10

**Comment by princemaple** [comment]
@asbjornenge I'm going to leave the merge to you in this one. :smile:

**Comment by asbjornenge** [comment]
Gave it a quick whirl. LGTM :smile:

**Comment by princemaple** [comment]
cc @vmg there is an update for docker syntax

**Comment by vmg** [comment]
@princemaple Thanks for the heads up! We've made all our language grammars for highlighting publicly available at https://github.com/github/linguist -- the repository also includes instructions on how to open a Pull Request to update one. Would you be so kind as to proposing the update on that repository? Thank you!

**Pull request merged**
